# Generated by Django 3.2.6 on 2021-09-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='f_name',
        ),
    ]
